sudo: required
services:
  - docker

before_install:
  - docker build -t trinitadewanti/docker-react -f Dockerfile.dev .

script:
  - docker run trinitadewanti/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-714755674953"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    
    